### ISSUE TITLE
Here is a question about the use of dicompot in Tpot

### ISSUE THREAD

**Issue by DAYceng** [nsmfoo/dicompot#5]
I scanned Tpot's ip address through Nmap, but dicompot did not record the related access records, and I checked the log in the dicompot container and there was no log record.

**Comment by nsmfoo** [comment]
@DAYceng  As I'm not up to date with the setup offered by T-Pot which bundles Dicompot, I can only give you generic suggestions, for more specific T-pot support, I suggest that you open a case with the T-pot team.

So in order for Dicompot to be able to record anything, you need to be able to access the service. So given that you have an IP address and that you can connect to the service with for example netcat: nc -v <IP> <PORT> , then your setup should work as expected. 

However if you are not you able to access the service, there there are most likely an issue with access, the service not started etc

I hope the above make sense, if not let me know

**Comment by nsmfoo** [comment]
I will close this case, if you still have any issues. Please let me know
