### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by azubkokshe** [nsmfoo/dicompot#6]
Hello! Have you used this server in production? How does it withstand loads? Is it stable?

**Comment by nsmfoo** [comment]
Hi @azubkokshe 

Dicompot have and is being deployed both as a stand alone installations, but also as bundled installation with other honeypot services through T-Pot at some scale (according to some feedback that I have been given and seen) 

So far I have not seen or gotten any feedback that it has stability issues, but I can't say that there is no such problems =).

But given the fact that Dicompot is a honeypot,  which is at it's core are a system that no one should talk to anyway, the amount of load that it should be able to handle, would in most cases not be that high. Obviously it should not fail easily either =)

Does that make sense? If not please let me know and I can expand on the above.

**Comment by azubkokshe** [comment]
@nsmfoo thanks! useful information! =)
